import 'dart:math';

/// ********************************************************************
/// Flashcard model
/// ********************************************************************
///
/// Represents a single flashcard loaded from JSON or generated by AI.
/// Flashcards have a front (question/prompt) and back (answer/explanation).
///
/// Example JSON object:
/// {
///   "id": 1,
///   "front": "What is the capital of France?",
///   "back": "Paris",
///   "explanation": "Paris is the capital and largest city of France."
/// }
///
class Flashcard {
  const Flashcard({
    required this.id,
    required this.front,
    required this.back,
    this.explanation,
  });

  /// Factory for creating a [Flashcard] from decoded JSON.
  factory Flashcard.fromJson(Map<String, dynamic> json) {
    return Flashcard(
      id: json['id'] as int,
      front: json['front'] as String,
      back: json['back'] as String,
      explanation: json['explanation'] as String?,
    );
  }

  /// Numeric identifier for the flashcard.
  final int id;

  /// The front side of the flashcard (question/prompt).
  final String front;

  /// The back side of the flashcard (answer).
  final String back;

  /// Optional explanation or additional context.
  ///
  /// This is typically provided for AI-generated flashcards based on study material.
  /// If present, indicates this is an AI-generated flashcard with additional context.
  final String? explanation;

  /// Converts this flashcard back to JSON.
  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'front': front,
      'back': back,
      if (explanation != null) 'explanation': explanation,
    };
  }

  /// Creates a copy of this flashcard with updated fields.
  Flashcard copyWith({
    int? id,
    String? front,
    String? back,
    String? explanation,
  }) {
    return Flashcard(
      id: id ?? this.id,
      front: front ?? this.front,
      back: back ?? this.back,
      explanation: explanation ?? this.explanation,
    );
  }

  /// Debug helper for logging.
  @override
  String toString() {
    return 'Flashcard(id: $id, front: $front, back: $back)';
  }
}

/// ********************************************************************
/// Flashcard Utilities
/// ********************************************************************
///
/// Utility functions for working with lists of flashcards.
///
class FlashcardUtils {
  /// Shuffles a list of flashcards.
  ///
  /// This prevents users from memorizing flashcard positions.
  /// A new random order is generated each time this is called.
  static List<Flashcard> shuffleFlashcards(List<Flashcard> flashcards) {
    final random = Random();
    final shuffled = List<Flashcard>.from(flashcards)..shuffle(random);
    return shuffled;
  }
}
